---
- hosts: db
  remote_user: root
  tasks: 
    - user:
        name: "{{item.username}}"
        group: "{{item.group}}"
        password: "{{item.passwd|password_hash('sha512')}}"
      with_items:
        -
          username: nb
          group: users
          passwd: '123456'
        - 
          username: wk
          group: bin
          passwd: banana
        - 
          username: dd
          group: daemon
          passwd: book
        - 
          username: jj
          group: mysql
          passwd: 123qqq...A
        - 
          username: xx
          group: root
          passwd: a
